F/vocdoni sdk organizations list
vocdoni/explorer-ui pull request #130
Opened 2023-05-17 10:14 UTC by selankon

Todos:

- [ ] Fix this https://github.com/vocdoni/interoperability/issues/63
- [ ] Merge this https://github.com/vocdoni/vocdoni-sdk/pull/174
- [ ] Check if filter work properly

2023-05-22 10:37 UTC, selankon commented on components/blocks/card/entity-card.tsx
> +  const entityLogo = organization?.account?.logo;
Use avatar and not logo!

2023-05-24 11:59 UTC, elboletaire requested changes

2023-05-24 11:59 UTC, elboletaire commented on components/blocks/card/entity-card.tsx
> +  const entityLogo = organization?.account?.logo;
Note that, as I said in the other PR, you can also use the provided organization components which do the logic behind the scenes. Specifically for the logo, the OrganizationAvatar component uses the avatar as main field, but uses the logo as a fallback (since logo is considered deprecated).

2023-06-07 08:51 UTC, selankon commented
@elboletaire this is ready for review

2023-06-12 07:57 UTC, elboletaire approved these changes

2023-06-12 08:13 UTC, elboletaire approved these changes
Just a FYI: since you upgraded @vocdoni/sdk to 0.0.13, you can stop using `ensure0x` from the old package `@vocdoni/common` and directly import it from the SDK instead.

2023-06-12 08:25 UTC, merged