Migrate organization details to SDK
vocdoni/explorer-ui pull request #133
Opened 2023-05-22 10:57 UTC by selankon

2023-05-24 11:56 UTC, elboletaire requested changes
You should consider using the provided Organization components in our chakra-components package. you would probably end up removing some components that you might not need anymore. Actually, the Image component used in explorer-ui is an exact copy of the one I created for vocdoni-app back in the day, and the one provided in chakra-components is a similar version (it uses an IPFS proxy URL instead of direct api calls to IPFS, which was cool in part, but at the same time was also overcomplicated).

So, in the case of the `OrganizationAvatar`, you can either chose to create a component based on that one, or you could try to replace the Image component you have, by the one provided by the chakra-components package.

2023-05-24 11:56 UTC, elboletaire commented on components/pages/organizations/details/index.tsx
> +      <CardImageHeader title={orgName} processImage={header} entityImage={avatar} />
I think you should consider replacing or updating this component with the `OrganizationAvatar` component.

2023-05-24 11:56 UTC, elboletaire commented on components/pages/organizations/details/index.tsx
> +            <Typography variant={TypographyVariant.Small}>{description}</Typography>
You could be using `OrganizationDescription` here

2023-06-12 09:01 UTC, selankon commented on components/pages/organizations/details/index.tsx
> +            <Typography variant={TypographyVariant.Small}>{description}</Typography>
https://github.com/vocdoni/explorer-ui/pull/133/files#diff-351efab9aa5fb2447dcbcbd9f0a72dd7a5a1082cb614f5689174e0f16ad24131R39

2023-06-12 09:07 UTC, merged