B/bulk bugfixes
vocdoni/explorer-ui pull request #167
Opened 2024-01-15 10:18 UTC by selankon

Multiple bug fixing

2024-01-16 15:52 UTC, elboletaire commented on components/pages/app/footer.tsx
> +    // },
Avoid leaving commented code please

2024-01-23 15:59 UTC, emmdim commented on components/pages/app/footer.tsx
> +    // },
fyi @selankon  :point_up:

2024-01-23 16:02 UTC, emmdim commented on components/pages/app/footer.tsx
> +      url: 'https://docs.vocdoni.io',
I think this should point to `https://developer.vocdoni.io` if I am not mistaken.
cc @jpaulet

2024-01-23 16:12 UTC, elboletaire requested changes

2024-01-23 16:12 UTC, elboletaire commented on i18n/locales/ca.json
> +            "invalid": "Invalida"
Should be `Invàlida` (missing accent)

2024-01-23 16:12 UTC, elboletaire commented on i18n/locales/es.json
> +            "invalid": "Invalida"
Should be "Inválida" (missing accent)

2024-01-23 16:13 UTC, emmdim reviewed
There are a series of warning during the build.
Could please you eliminate the ones related to 
`@typescript-eslint/no-unused-vars`
and `react-hooks/exhaustive-deps` @selankon ?
You can find them by doing a build locally as well

2024-01-23 16:13 UTC, emmdim commented on components/pages/app/footer.tsx
> +      url: 'https://help.aragon.org/collection/54-vocdoni-user-guide',
This link does not work correctly. Where should it point to? cc @jpaulet

2024-01-23 16:13 UTC, emmdim commented on components/pages/app/footer.tsx
> +      url: 'https://blog.vocdoni.io',
FYI this leads in the aragon based blog @jpaulet 
Is this ok?

2024-01-23 16:40 UTC, jpaulet commented on components/pages/app/footer.tsx
> +      url: 'https://docs.vocdoni.io',
100%, it must point to https://developer.vocdoni.io

2024-01-23 16:42 UTC, jpaulet commented on components/pages/app/footer.tsx
> +      url: 'https://help.aragon.org/collection/54-vocdoni-user-guide',
Right now, I would point this link to our "Support" channel on Discord: https://discord.gg/sM7UhAGY53

2024-01-23 16:44 UTC, jpaulet commented on components/pages/app/footer.tsx
> +      url: 'https://blog.vocdoni.io',
For the moment yes. We are moving the blog from Aragon->Vocdoni, but the work will start this week/next week. It's OK for now to point to the Aragon blog, but **changing the current link to: https://blog.aragon.org/vocdoni/**

2024-01-25 12:15 UTC, selankon commented on components/pages/app/footer.tsx
> +      url: 'https://help.aragon.org/collection/54-vocdoni-user-guide',
FYI @jpaulet there are already a discord channel on the "support" link:

https://github.com/vocdoni/explorer-ui/blob/8485488e8d23027fcf373c6eab89885aec327bd9/components/pages/app/footer.tsx#L41-L47

Which is invalid. Should I preserve the help link or the support one? (correcting with the working discord link)

2024-01-25 12:21 UTC, selankon commented on components/pages/app/footer.tsx
> +      url: 'https://blog.vocdoni.io',
beb440e

2024-01-25 12:21 UTC, selankon commented on i18n/locales/es.json
> +            "invalid": "Invalida"
beb440e

2024-01-25 12:21 UTC, selankon commented on i18n/locales/ca.json
> +            "invalid": "Invalida"
beb440e

2024-01-25 12:21 UTC, selankon commented on components/pages/app/footer.tsx
> +    // },
beb440e

2024-01-25 12:29 UTC, jpaulet commented on components/pages/app/footer.tsx
> +      url: 'https://help.aragon.org/collection/54-vocdoni-user-guide',
Then, we can remove the "help" link and update the support one with the new link.

2024-01-25 12:51 UTC, selankon commented
> There are a series of warning during the build. Could please you eliminate the ones related to `@typescript-eslint/no-unused-vars` and `react-hooks/exhaustive-deps` @selankon ? You can find them by doing a build locally as well

This is done on 87b5eb5

2024-02-16 09:30 UTC, selankon commented
This is ready for merge @emmdim

2024-02-27 11:04 UTC, elboletaire approved these changes

2024-02-27 11:08 UTC, merged