Delete duplicated line
vocdoni/explorer-ui pull request #66
Opened 2023-02-21 13:33 UTC by selankon

2023-02-27 15:45 UTC, elboletaire commented on .github/workflows/main.yml
> +        run: npm run test
FYI "test" among with "start" do not need the usage of "run"

2023-02-27 15:46 UTC, elboletaire commented on .github/workflows/main.yml
> +        run: npm run test
Reasons I love yarn: not required in any script + you can even run binaries in your node_modules by just running `yarn cmd_in_node_modules` (i.e. yarn tsc, in case you don't have tsc installed globally)

2023-02-27 15:47 UTC, elboletaire requested changes

2023-02-27 15:47 UTC, elboletaire commented on package.json
> +    "test": "jest test"
Why "jest test"? Shouldn't be enough with just `jest`? Or you have a path named `test`? 🤔

2023-02-27 15:47 UTC, elboletaire commented on test/test.ts
> +})
not sure if this test is required at all 😅

2023-03-01 12:43 UTC, selankon commented on .github/workflows/main.yml
> +        run: npm run test
I tried locally and `npm test` fail, while `npm run test` no... 

Anyway, I'm going to deprecate npm in favor of yarn ASAP

2023-03-01 12:44 UTC, selankon commented on test/test.ts
> +})
Absolutely not, but I'm planing to start developing tests. (at the early beginning we decided to don't do TDD but after SDK implementation I would like to add test before implementing new features)

2023-03-01 12:46 UTC, selankon commented on package.json
> +    "test": "jest test"
You are right fba36ef

2023-03-01 12:47 UTC, elboletaire approved these changes

2023-03-01 12:48 UTC, merged