F/upgrade to react 18
vocdoni/explorer-ui pull request #67
Opened 2023-02-24 10:12 UTC by selankon

2023-02-27 15:52 UTC, elboletaire requested changes

2023-02-27 15:52 UTC, elboletaire commented on package.json
> +    "@vocdoni/react-hooks": "file:vocdoni-react-hooks.tgz",
Don't forget to get this back to how should it be (or either remove the entire dependency if required, ofc).

2023-03-01 10:04 UTC, elboletaire requested changes

2023-03-01 10:04 UTC, elboletaire commented on components/blocks/list-items.tsx
>            </VoteListItemTitle> : null}
Rather than using 

```jsx
{ title ? <something /> : null }
```

better use:

```jsx
{ title && <something /> }
```

2023-03-01 10:09 UTC, selankon commented on components/blocks/list-items.tsx
>            </VoteListItemTitle> : null}
Thats true! :+1: 2b25c3c

2023-03-01 10:13 UTC, elboletaire commented on components/blocks/list-items.tsx
>            </VoteListItemTitle> : null}
haha that commit you're pointing to shows me a completely commented file 😅

2023-03-01 10:38 UTC, selankon commented
The only remaining thing to get this merged is to update the `@vocdoni/react-hooks` peer dependency from React 17 to `react 17 | 18`.

2023-03-01 10:58 UTC, selankon commented on components/blocks/list-items.tsx
>            </VoteListItemTitle> : null}
Lol I just saw it I add wrong file... This is the good one 2452b1f

2023-03-01 11:21 UTC, elboletaire requested changes
Minor indentation issue, but other than that LGTM

2023-03-01 11:21 UTC, elboletaire commented on components/elements/date-picker.tsx
> +                        } : IDateTimePickerProps) => {
This indentation doesn't look good

2023-03-10 12:13 UTC, selankon commented on components/elements/date-picker.tsx
> +                        } : IDateTimePickerProps) => {
I will do lintfix in a sepparated PR

2023-03-10 12:20 UTC, elboletaire approved these changes

2023-03-13 07:48 UTC, merged