Implement overwriteCount
vocdoni/explorer-ui pull request #68
Opened 2023-02-27 10:11 UTC by selankon

Related https://github.com/vocdoni/interoperability/issues/1

2023-02-27 15:50 UTC, elboletaire requested changes
I see lots of "missing" translations. Other than that, and the minor change I commented about that single if, LGTM.

2023-03-03 11:38 UTC, selankon commented on components/pages/envelopes/details/index.tsx
> +              envelope.overwriteCount > 0 && (<Typography variant={TypographyVariant.Small}>
:tada: b637978 :tada:

2023-03-03 11:39 UTC, selankon commented
> I see lots of "missing" translations. Other than that, and the minor change I commented about that single if, LGTM.

Will fix it from master

2023-03-03 11:40 UTC, elboletaire approved these changes

2023-03-03 11:45 UTC, merged